-- LIFEOS - MIGRACAO 041: BIBLIOTECA INICIAL DE RECEITAS
-- Receitas autorais/curadas para a Casa, alinhadas ao Guia Alimentar do
-- Ministerio da Saude. Nao cria biblioteca paralela: reutiliza refeicoes.
--
-- Referencias de curadoria:
-- https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel
-- https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel
-- https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimento-saudavel/2o-passo

with receitas(nome,tipo,porcoes,tempo,modo,observacoes,fonte) as (
  values
  ('Frango cremoso com brócolis','ambos',4,25,
   'Doure o frango em cubos com alho e cebola. Junte o brócolis já cozido rapidamente no vapor. Desligue o fogo e misture uma pequena porção de requeijão até envolver. Ajuste temperos e sirva.',
   'Boa base para arroz e feijão ou batata. Requeijão entra como complemento, não como base do prato.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Sassami com mostarda e batata na Air Fryer','ambos',2,30,
   'Tempere o sassami com alho, limão, ervas e mostarda. Corte a batata em pedaços pequenos. Asse a batata primeiro e acrescente o frango até dourar e cozinhar por completo.',
   'Prática para dias de trabalho. Complete com salada ou legumes.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Sobrecoxa com cenoura e cebola na Air Fryer','ambos',3,35,
   'Tempere as sobrecoxas com alho, limão, páprica e ervas. Asse com cenoura e cebola em pedaços, virando na metade do tempo, até cozinhar por completo.',
   'Retirar excesso aparente de pele/gordura é opcional conforme preferência e porção.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Frango desfiado colorido com legumes','ambos',4,25,
   'Refogue cebola e alho, acrescente frango já cozido e desfiado, cenoura, tomate, milho e ervilhas. Cozinhe apenas até os legumes ficarem macios e finalize com cheiro-verde.',
   'Funciona como recheio de sanduíche, wrap ou acompanhamento de arroz e feijão.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Frango com couve-flor e páprica','ambos',2,25,
   'Tempere o frango em cubos com alho, limão e páprica. Doure em frigideira. Cozinhe a couve-flor rapidamente no vapor e misture ao frango no final.',
   'Preparação simples e de baixo atrito para a semana.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Carne moída com abobrinha e cenoura','ambos',4,25,
   'Doure a carne moída com alho e cebola. Acrescente cenoura e abobrinha em cubos pequenos e cozinhe até ficarem macias, mantendo alguma textura. Finalize com cheiro-verde.',
   'Pode acompanhar arroz, feijão, batata ou purê.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Carne moída com purê de inhame','ambos',4,35,
   'Cozinhe o inhame e amasse com pequena quantidade de leite ou água do cozimento. Prepare a carne moída com alho, cebola e tomate. Sirva a carne sobre o purê e acompanhe com salada.',
   'O inhame entra como uma das opções de carboidrato da refeição.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimento-saudavel/2o-passo'),
  ('Acém de panela com legumes','ambos',4,45,
   'Sele a carne em cubos, junte alho, cebola e tomate. Cozinhe sob pressão com água suficiente. Abra a panela, acrescente cenoura e batata e termine sem pressão até os legumes ficarem macios.',
   'Boa receita para preparar base e congelar em porções.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Bife acebolado com couve','ambos',2,20,
   'Tempere os bifes pouco antes do preparo. Sele em frigideira bem quente no ponto desejado, retire e faça a cebola na mesma panela. Sirva com couve rapidamente refogada ou cozida.',
   'O ponto da carne pode ser finalizado separadamente para cada pessoa.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Almôndegas caseiras ao molho de tomate','ambos',4,35,
   'Misture carne moída com cebola, alho, cheiro-verde e aveia suficiente para dar liga. Modele, doure e termine o cozimento em molho de tomate com temperos naturais.',
   'Pode ser servida com arroz, purê, legumes ou macarrão.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Filé mignon suíno com mostarda e ervas','ambos',3,30,
   'Corte o filé suíno em medalhões, tempere com alho, limão, mostarda e ervas. Doure em frigideira ou Air Fryer e cozinhe até o centro estar completamente cozido.',
   'Proteína prática para variar do frango.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Lombo suíno com batata-doce','ambos',3,35,
   'Tempere o lombo em tiras ou bifes com alho, limão e ervas. Asse ou grelhe. Prepare a batata-doce em cubos na Air Fryer e sirva com salada crua.',
   'Pode substituir batata-doce por batata inglesa, aipim ou inhame.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimento-saudavel/2o-passo'),
  ('Tilápia com limão e brócolis','ambos',2,22,
   'Tempere os filés com limão, alho e ervas. Asse na Air Fryer ou frigideira até cozinhar por completo. Faça o brócolis rapidamente no vapor e tempere ao servir.',
   'Receita rápida para preparar a proteína na hora.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Peixe ao molho rápido de tomate','ambos',3,30,
   'Refogue alho e cebola, acrescente tomate picado ou molho de tomate simples e deixe apurar. Coloque os filés de peixe, tampe e cozinhe em fogo baixo até ficarem macios.',
   'Combina com arroz e feijão ou batata cozida.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Sardinha com batata e salada de tomate','ambos',2,20,
   'Cozinhe as batatas em cubos. Misture tomate, cebola, cheiro-verde e limão. Sirva com sardinha escorrida e a batata, ajustando azeite e sal no prato.',
   'Opção de emergência usando item de despensa.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Omelete de brócolis e muçarela','ambos',2,15,
   'Bata os ovos, tempere e misture brócolis já cozido e uma pequena porção de muçarela. Cozinhe em frigideira antiaderente em fogo baixo até firmar.',
   'Funciona especialmente bem como refeição noturna.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Omelete de couve, tomate e cebola','ambos',2,15,
   'Bata os ovos. Refogue rapidamente cebola e couve, acrescente tomate e despeje os ovos. Cozinhe dos dois lados ou tampado até firmar.',
   'Refeição rápida com ingredientes comuns da Casa.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Bowl de arroz, feijão, frango e legumes','almoco',2,20,
   'Aqueça arroz e feijão já preparados. Faça o frango na Air Fryer ou frigideira. Complete o prato com legumes preparados na hora e salada crua.',
   'Modelo de montagem, não receita rígida. As porções são definidas no Ritmo de cada pessoa.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimentacao-saudavel/alimentacao-saudavel'),
  ('Macarrão com atum, tomate e brócolis','ambos',3,25,
   'Cozinhe o macarrão até ficar al dente. Faça molho rápido com alho, tomate e atum escorrido. Misture brócolis cozido no vapor e envolva o macarrão.',
   'Macarrão pode compor uma refeição equilibrada quando porção e acompanhamentos são planejados.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimento-saudavel/2o-passo'),
  ('Escondidinho de carne moída e aipim','ambos',4,45,
   'Cozinhe e amasse o aipim com pequena quantidade de leite ou água do cozimento. Prepare a carne moída com alho, cebola e tomate. Monte em recipiente próprio para micro-ondas e aqueça até ficar uniforme.',
   'Pode ser porcionado e congelado. Sem forno, finalize no micro-ondas.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-pessoa-idosa/alimento-saudavel/2o-passo'),

  ('Banana com iogurte e granola','lanche',1,5,
   'Corte a banana, cubra com iogurte e finalize com uma porção medida de granola.',
   'Lanche rápido. A granola entra medida, não comida direto do pacote.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Iogurte natural com maçã e aveia','lanche',1,5,
   'Pique a maçã, misture com iogurte natural e aveia. Canela é opcional.',
   'Fruta e iogurte formam uma opção prática para intervalos.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Sanduíche de ovo e tomate','cafe',1,10,
   'Prepare dois ovos mexidos. Monte no pão com tomate e, se desejar, pequena porção de queijo ou requeijão.',
   'Alternativa para aumentar proteína no café da manhã.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Sanduíche de frango e salada','lanche',1,8,
   'Use frango já preparado ou desfiado. Monte no pão com folhas, tomate e pequena porção de requeijão ou mostarda.',
   'Use a preparação-base de frango para reduzir o trabalho durante a semana.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Ovos cozidos com fruta','lanche',1,12,
   'Cozinhe os ovos e sirva com uma fruta inteira de preferência.',
   'Pode deixar poucos ovos cozidos prontos para facilitar dias de trabalho.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Tapioca com ovo e queijo','cafe',1,12,
   'Prepare a tapioca em frigideira. Recheie com ovos mexidos e pequena porção de queijo.',
   'Pode entrar no café da manhã ou lanche, alternando com pão.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Banana morna com canela e iogurte','lanche',1,6,
   'Aqueça a banana rapidamente no micro-ondas com canela e sirva com iogurte.',
   'Opção doce de porção individual para substituir sobremesas grandes em casa.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Copo de frutas com iogurte','lanche',1,7,
   'Pique duas frutas disponíveis e sirva com iogurte natural.',
   'Use frutas que precisam ser consumidas primeiro para reduzir desperdício.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Milho cozido com ovos','lanche',1,15,
   'Cozinhe a espiga de milho até ficar macia. Sirva com ovos cozidos ou mexidos.',
   'Milho e ovos são uma combinação prática para pequena refeição.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel'),
  ('Batata-doce com ovo mexido','lanche',1,15,
   'Cozinhe ou asse a batata-doce em porção individual e prepare ovos mexidos no momento de comer.',
   'Boa opção para dias com mais atividade física.',
   'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/eu-quero-me-alimentar-melhor/noticias/2022/pequenas-refeicoes-durante-o-dia-cinco-dicas-para-ter-um-lanche-saudavel')
)
insert into public.refeicoes (
  casa_id,nome,tipo,porcoes,tempo_minutos,modo_preparo,observacoes,fonte_url,criada_por,atualizado_em
)
select
  c.id, r.nome, r.tipo, r.porcoes, r.tempo, r.modo, r.observacoes, r.fonte,
  (select u.id from public.usuarios u where u.casa_id = c.id order by u.criado_em nulls last limit 1),
  now()
from public.casa c
cross join receitas r
where not exists (
  select 1 from public.refeicoes ex
  where ex.casa_id = c.id and lower(trim(ex.nome)) = lower(trim(r.nome))
);

with ingredientes(receita,nome,quantidade,unidade) as (
  values
  ('Frango cremoso com brócolis','peito de frango',600,'g'),
  ('Frango cremoso com brócolis','brócolis',300,'g'),
  ('Frango cremoso com brócolis','requeijão',80,'g'),
  ('Frango cremoso com brócolis','alho',2,'dentes'),
  ('Frango cremoso com brócolis','cebola',1,'un'),
  ('Sassami com mostarda e batata na Air Fryer','sassami',400,'g'),
  ('Sassami com mostarda e batata na Air Fryer','batata',400,'g'),
  ('Sassami com mostarda e batata na Air Fryer','mostarda',1,'colher sopa'),
  ('Sobrecoxa com cenoura e cebola na Air Fryer','sobrecoxa',600,'g'),
  ('Sobrecoxa com cenoura e cebola na Air Fryer','cenoura',2,'un'),
  ('Sobrecoxa com cenoura e cebola na Air Fryer','cebola',1,'un'),
  ('Frango desfiado colorido com legumes','frango cozido e desfiado',500,'g'),
  ('Frango desfiado colorido com legumes','cenoura',1,'un'),
  ('Frango desfiado colorido com legumes','tomate',2,'un'),
  ('Frango desfiado colorido com legumes','milho',100,'g'),
  ('Frango desfiado colorido com legumes','ervilha',100,'g'),
  ('Frango com couve-flor e páprica','peito de frango',400,'g'),
  ('Frango com couve-flor e páprica','couve-flor',300,'g'),
  ('Carne moída com abobrinha e cenoura','carne moída',500,'g'),
  ('Carne moída com abobrinha e cenoura','abobrinha',1,'un'),
  ('Carne moída com abobrinha e cenoura','cenoura',1,'un'),
  ('Carne moída com purê de inhame','carne moída',500,'g'),
  ('Carne moída com purê de inhame','inhame',600,'g'),
  ('Acém de panela com legumes','acém',700,'g'),
  ('Acém de panela com legumes','cenoura',2,'un'),
  ('Acém de panela com legumes','batata',3,'un'),
  ('Bife acebolado com couve','bife',400,'g'),
  ('Bife acebolado com couve','cebola',1,'un'),
  ('Bife acebolado com couve','couve',1,'maço'),
  ('Almôndegas caseiras ao molho de tomate','carne moída',500,'g'),
  ('Almôndegas caseiras ao molho de tomate','aveia',40,'g'),
  ('Almôndegas caseiras ao molho de tomate','molho de tomate',300,'g'),
  ('Filé mignon suíno com mostarda e ervas','filé mignon suíno',500,'g'),
  ('Filé mignon suíno com mostarda e ervas','mostarda',1,'colher sopa'),
  ('Lombo suíno com batata-doce','lombo suíno',500,'g'),
  ('Lombo suíno com batata-doce','batata-doce',500,'g'),
  ('Tilápia com limão e brócolis','filé de tilápia',400,'g'),
  ('Tilápia com limão e brócolis','brócolis',300,'g'),
  ('Peixe ao molho rápido de tomate','filé de peixe',500,'g'),
  ('Peixe ao molho rápido de tomate','tomate',4,'un'),
  ('Sardinha com batata e salada de tomate','sardinha',2,'latas'),
  ('Sardinha com batata e salada de tomate','batata',400,'g'),
  ('Sardinha com batata e salada de tomate','tomate',2,'un'),
  ('Omelete de brócolis e muçarela','ovos',6,'un'),
  ('Omelete de brócolis e muçarela','brócolis',200,'g'),
  ('Omelete de brócolis e muçarela','muçarela',60,'g'),
  ('Omelete de couve, tomate e cebola','ovos',6,'un'),
  ('Omelete de couve, tomate e cebola','couve',4,'folhas'),
  ('Omelete de couve, tomate e cebola','tomate',1,'un'),
  ('Bowl de arroz, feijão, frango e legumes','arroz cozido',240,'g'),
  ('Bowl de arroz, feijão, frango e legumes','feijão preto',2,'conchas'),
  ('Bowl de arroz, feijão, frango e legumes','peito de frango',320,'g'),
  ('Bowl de arroz, feijão, frango e legumes','legumes variados',300,'g'),
  ('Macarrão com atum, tomate e brócolis','macarrão',240,'g'),
  ('Macarrão com atum, tomate e brócolis','atum',2,'latas'),
  ('Macarrão com atum, tomate e brócolis','tomate',3,'un'),
  ('Macarrão com atum, tomate e brócolis','brócolis',250,'g'),
  ('Escondidinho de carne moída e aipim','carne moída',500,'g'),
  ('Escondidinho de carne moída e aipim','aipim',700,'g'),
  ('Banana com iogurte e granola','banana',1,'un'),
  ('Banana com iogurte e granola','iogurte',170,'g'),
  ('Banana com iogurte e granola','granola',25,'g'),
  ('Iogurte natural com maçã e aveia','iogurte natural',170,'g'),
  ('Iogurte natural com maçã e aveia','maçã',1,'un'),
  ('Iogurte natural com maçã e aveia','aveia',20,'g'),
  ('Sanduíche de ovo e tomate','pão de forma',2,'fatias'),
  ('Sanduíche de ovo e tomate','ovos',2,'un'),
  ('Sanduíche de ovo e tomate','tomate',0.5,'un'),
  ('Sanduíche de frango e salada','pão de forma',2,'fatias'),
  ('Sanduíche de frango e salada','frango desfiado',100,'g'),
  ('Sanduíche de frango e salada','tomate',0.5,'un'),
  ('Ovos cozidos com fruta','ovos',2,'un'),
  ('Ovos cozidos com fruta','fruta',1,'un'),
  ('Tapioca com ovo e queijo','goma de tapioca',50,'g'),
  ('Tapioca com ovo e queijo','ovos',2,'un'),
  ('Tapioca com ovo e queijo','muçarela',25,'g'),
  ('Banana morna com canela e iogurte','banana',1,'un'),
  ('Banana morna com canela e iogurte','iogurte',170,'g'),
  ('Copo de frutas com iogurte','frutas variadas',200,'g'),
  ('Copo de frutas com iogurte','iogurte natural',170,'g'),
  ('Milho cozido com ovos','milho em espiga',1,'un'),
  ('Milho cozido com ovos','ovos',2,'un'),
  ('Batata-doce com ovo mexido','batata-doce',150,'g'),
  ('Batata-doce com ovo mexido','ovos',2,'un')
)
insert into public.refeicao_ingredientes (refeicao_id,nome,quantidade,unidade)
select r.id, i.nome, i.quantidade, i.unidade
from ingredientes i
join public.refeicoes r on r.nome = i.receita
where not exists (
  select 1 from public.refeicao_ingredientes x
  where x.refeicao_id = r.id and lower(trim(x.nome)) = lower(trim(i.nome))
);
