-- LIFEOS - HISTORICO
-- Esta versão intermediária foi substituída por 049_pagamentos_multiplos_acertos.sql.
-- Mantida apenas para preservar o histórico do repositório.
-- Não executar operações aqui: a migração canônica de pagamentos em lote é
-- db/049_pagamentos_multiplos_acertos.sql.
