plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.lifeos.gumate'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.lifeos.gumate'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '0.1.0'

        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE*', 'META-INF/NOTICE*']
        }
    }
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.18.1@aar'
    implementation 'com.alphacephei:vosk-android:0.3.75@aar'
}
